version: "3.8"

services:
  mysql_db:
      image: mysql
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./docker/mysql/database:/var/lib/mysql # Database
      restart: always
      env_file: .env.local
      ports: 
        - 3306:3306

  phpmyadmin:
      image: phpmyadmin:5
      container_name: blog_pma
      restart: always
      env_file: .env.local
      ports: 
        - 8080:80
      depends_on:
        - mysql_db
 